const typography = {
  letterSpacings: {
    xs: '-0.05rem',
    sm: '-0.025rem',
    md: '0',
    lg: '0.025rem',
    xl: '0.05rem',
    xxl: '0.1rem',
  },
  lineHeights: {
    xxs: '0.25rem',
    xs: '0.375rem',
    xm: '0.5rem',
    md: '1rem',
    lg: '1.7rem',
    xl: '2.25rem',
    xxl: '3rem',
  },
  fontWeights: {
    xxxs: 100,
    xxs: 200,
    xs: 300,
    md: 400,
    lg: 500,
    xl: 600,
    xxl: 700,
    xxxl: 800,
    xxxxxl: 900,
  },
  fonts: {
    heading: `-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
    body: `-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
    mono: `SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace`,
  },
  fontSizes: {
    xxxxs: '0.75rem',
    xxxs: '0.875rem',
    xxs: '1rem',
    xs: '1.125rem',
    sm: '1.25rem',
    md: '1.5rem',
    lg: '1.875rem',
    xl: '2.25rem',
    xxl: '3rem',
    xxxl: '3.75rem',
    xxxxl: '4.5rem',
    xxxxxl: '6rem',
  },
};

export default typography;
