const typography = {
  letterSpacings: {
    xxxxs: '-0.2rem',
    xxxs: '-0.15rem',
    xxs: '-0.1rem',
    xs: '-0.05rem',
    sm: '-0.025rem',
    md: '0',
    lg: '0.025rem',
    xl: '0.05rem',
    xxl: '0.1rem',
    xxxl: '0.15rem',
    xxxxl: '0.2rem',
  },
  lineHeights: {
    xxxxs: '0.09rem',
    xxxs: '0.15rem',
    xxs: '0.25rem',
    xs: '0.375rem',
    xm: '0.5rem',
    md: '1rem',
    lg: '1.7rem',
    xl: '2.25rem',
    xxl: '3rem',
    xxxl: '3.5rem',
    xxxxl: '4rem',
  },
  fontWeights: {
    xxxxs: 50,
    xxxs: 100,
    xxs: 200,
    xs: 300,
    sm: 400,
    md: 500,
    lg: 600,
    xl: 700,
    xxl: 800,
    xxxl: 900,
    xxxxl: 1000,
  },
  fonts: {
    heading: `-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
    body: `-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
    mono: `SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace`,
  },
  fontSizes: {
    xxxxs: '0.7rem',
    xxxs: '0.85rem',
    xxs: '1rem',
    xs: '1.125rem',
    sm: '1.25rem',
    md: '1.4rem',
    lg: '1.875rem',
    xl: '2.25rem',
    xxl: '3rem',
    xxxl: '3.5rem',
    xxxxl: '4rem',
  },
};

export default typography;
